name: Metrics
on:
  # Schedule daily updates
  schedule: [ { cron: "0 0 * * *" } ]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      actions: write
      contents: write
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Brussels
          optimize: css, xml, svg
          experimental_features: --optimize-svg
          output_condition: data-changed
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_licenses: yes
          plugin_stars: yes
          plugin_introduction: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_people: yes
          plugin_achievements: yes
          plugin_activity: yes
          plugin_calendar: yes
          plugin_notable: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 766786
          plugin_rss: yes
          plugin_rss_source: https://amedee.be/feed/
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 6
