name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Brussels
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_licenses: yes
          plugin_stars: yes
          plugin_introduction: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_people: yes
          plugin_achievements: yes
          plugin_activity: yes
          plugin_calendar: yes
          plugin_notable: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 766786
          plugin_rss: yes
          plugin_rss_source: https://amedee.be/feed/
